#!/bin/bash

#
# This script simply counts all lines from authentication log and finds out
# how many failed logins it gave on your server today
#
output "Failed login count: $(cat /var/log/auth.log | grep 'Failed password' | wc -l)"

