#!/bin/bash

#
# This script counts all failed logins for the current day 
#

failed_login_count=$(cat /var/log/auth.log | grep 'Failed password' | grep "$(date +"%b")  $(date +'%-d')" | wc -l)
output "Failed login count: $(echo $failed_login_count)"

